version: "2"

plugins:
  duplication:
    enable: true
  fixme:
    enable: true
  markdownlint:
    enable: true
  pep8:
    enabled: true
  radon:
    enabled: true
  shellcheck:
    enabled: true
  sonar-python:
    enabled: true
